HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$HOME/.zsh_history

setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
unsetopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
